### PR TITLE
Support for STM32

### PR DESCRIPTION
**Pull request by olofwalker**
This PR adds support for two STM32 chipsets 

- stm32h743zi
- stm32f767zi

The only difference between these and the NRF examples is that due to a difference in memory layout, the build scripts have been modified to be configured based on the selected feature.

### CODE REVIEW

**Review by huntc — COMMENTED** [review]
Thanks so much for this!

I'm now wondering if we can do better though. It’s entirely on me that I’ve introduced the nrf-app, stm-app convention. I think this is a mistake though given how unifying Embassy makes things. Perhaps I should’ve used embedded-app to capture multiple targets. The board support convention I’ve got should be enough, although I recognise that they’ll be Api differences. Perhaps those can be felt with via feature checking though. 

Wdyt?

**Review by huntc — APPROVED** [review]
I’m can also do the refactoring. Thanks again for the effort.

**Comment by olofwalker** [comment]
> Thanks so much for this!
> 
> I'm now wondering if we can do better though. It’s entirely on me that I’ve introduced the nrf-app, stm-app convention. I think this is a mistake though given how unifying Embassy makes things. Perhaps I should’ve used embedded-app to capture multiple targets. The board support convention I’ve got should be enough, although I recognise that they’ll be Api differences. Perhaps those can be felt with via feature checking though.
> 
> Wdyt?

Yea, there is some duplication going on, so a successful refactoring would come down to good use of feature checking. One thing that make C/C++ terrible is the arbitrary use of conditional code paths, while often saving some duplication, it also made code hard to read.

**Comment by huntc** [comment]
Closing in favour of #2. Thanks so much for the help you provided towards that.

**Pull request closed without merging**
